import {describe,it,expect} from 'vitest';
import {applyCommand,conditions,createActivity,reconcile} from '../worker/engine';
import type {Activity,Notice,Rules} from '../worker/types';
const t=Date.UTC(2026,8,5,10);
const rules=(r:Partial<Rules>={}):Rules=>({minPeople:2,maxPeople:3,waitlist:true,recruitmentDeadline:t+3600000,startsAt:t+7200000,endsAt:t+10800000,registrationDeadline:t+6900000,promotionDeadline:t+6900000,repairMinutes:10,venueRequired:false,minTalks:0,minCohosts:0,minHosts:0,allowRoleOverlap:true,continuousVenue:true,continuousTalks:true,continuousCohosts:true,continuousHosts:true,addressVisibility:'participants',...r});
function event(r:Partial<Rules>={}):Activity{const e=createActivity({title:'测试咖啡',city:'Amsterdam',description:'',rules:rules(r)},'owner',t);applyCommand(e,{action:'publish'},'owner',t,[]);return e;}
function act(e:Activity,action:string,user:string,at=t+1000,more:Record<string,unknown>={}){const out:Notice[]=[];reconcile(e,at,out);applyCommand(e,{action,...more},user,at,out);return out;}
describe('确定性业务规则',()=>{
 it('校验规则与发布锁定',()=>{expect(()=>event({minPeople:4})).toThrow();const e=event();expect(()=>act(e,'edit','owner')).toThrow('锁定');});
 it('截止满足则成团，不足则取消且不能救活',()=>{const e=event();act(e,'join','a');act(e,'join','b');reconcile(e,t+3600001,[]);expect(e.status).toBe('confirmed');expect(e.receipts.at(-1)?.at).toBe(t+3600000);const bad=event();reconcile(bad,t+3600001,[]);expect(bad.status).toBe('cancelled');expect(()=>act(bad,'join','a',t+3600002)).toThrow();});
 it('退出优先候补并发入选通知',()=>{const e=event({maxPeople:2});for(const u of ['a','b','c'])act(e,'join',u);reconcile(e,t+3600000,[]);const out=act(e,'leave','a',t+3700000);expect(e.participants.find(p=>p.userId==='c')?.status).toBe('joined');expect(out.some(n=>n.userId==='c'&&n.subject.includes('入选'))).toBe(true);expect(e.repairs).toHaveLength(0);});
 it('始终维持最低人数，不足新报名不延长倒计时，补齐才解除',()=>{const e=event({minPeople:3,maxPeople:5});for(const u of ['a','b','c'])act(e,'join',u);reconcile(e,t+3600000,[]);act(e,'leave','a',t+3700000);const deadline=e.repairs[0].deadline;act(e,'leave','b',t+3701000);act(e,'join','d',t+3702000);expect(e.repairs[0].deadline).toBe(deadline);act(e,'join','f',t+3703000);expect(e.status).toBe('confirmed');expect(e.repairs).toHaveLength(0);});
 it('报名截止不阻止人数补齐，到期不足取消',()=>{const e=event({registrationDeadline:t+3600000});act(e,'join','a');act(e,'join','b');reconcile(e,t+3600000,[]);act(e,'leave','a',t+3700000);act(e,'join','c',t+3700100);expect(e.status).toBe('confirmed');act(e,'leave','b',t+3700200);reconcile(e,t+4400000,[]);expect(e.status).toBe('cancelled');});
 it('场地和人数独立异常，未审核提案无效',()=>{const e=event({venueRequired:true});act(e,'apply','v',t+1000,{kind:'venue',title:'场地',detail:'',address:'地址',capacity:3});act(e,'review','owner',t+2000,{applicationId:e.applications[0].id,approved:true});act(e,'join','a');act(e,'join','b');reconcile(e,t+3600000,[]);act(e,'withdraw','v',t+3700000,{applicationId:e.applications[0].id});act(e,'leave','a',t+3700100);expect(e.repairs.map(r=>r.key).sort()).toEqual(['people','venue']);act(e,'apply','v2',t+3700200,{kind:'venue',title:'新场地',detail:'',address:'地址2',capacity:3});expect(e.repairs).toHaveLength(2);act(e,'review','owner',t+3700300,{applicationId:e.applications[1].id,approved:true});expect(e.repairs.map(r=>r.key)).toEqual(['people']);});
 it('协办权限批准生效、退出立即撤销、不可人工取消',()=>{const e=event();act(e,'apply','co',t+1000,{kind:'cohost',title:'申请',detail:''});act(e,'apply','sp',t+1001,{kind:'talk',title:'分享',detail:'',duration:10});expect(()=>act(e,'review','co',t+1002,{applicationId:e.applications[1].id,approved:true})).toThrow();act(e,'review','owner',t+1003,{applicationId:e.applications[0].id,approved:true});act(e,'review','co',t+1004,{applicationId:e.applications[1].id,approved:true});expect(()=>act(e,'cancel','co',t+1005,{reason:'取消'})).toThrow();act(e,'withdraw','co',t+1006,{applicationId:e.applications[0].id});expect(e.applications[1].status).toBe('approved');expect(()=>act(e,'review','co',t+1007,{applicationId:e.applications[1].id,approved:false})).toThrow();});
  it('兼任规则与一人一位',()=>{const e=event({allowRoleOverlap:false,minCohosts:1,minHosts:1});for(const kind of ['cohost','host']){act(e,'apply','same',t+1000,{kind,title:'申请',detail:''});act(e,'review','owner',t+2000,{applicationId:e.applications.at(-1)!.id,approved:true});}act(e,'join','same');act(e,'join','same');expect(conditions(e).find(c=>c.key==='people')?.current).toBe(1);expect(conditions(e).find(c=>c.key==='roles')?.satisfied).toBe(false);});
  it('报名时保存偏好且已报名者可以更新',()=>{const e=event();act(e,'join','a',t+1000,{timePreference:'周六下午',placePreference:'Amsterdam'});expect(e.participants[0]).toMatchObject({timePreference:'周六下午',placePreference:'Amsterdam'});act(e,'join','a',t+2000,{timePreference:'周日下午',placePreference:'Utrecht'});expect(e.participants).toHaveLength(1);expect(e.participants[0]).toMatchObject({timePreference:'周日下午',placePreference:'Utrecht'});});
 it('活动结束是终态',()=>{const e=event();act(e,'join','a');act(e,'join','b');reconcile(e,t+10800001,[]);expect(e.status).toBe('completed');expect(()=>act(e,'join','c',t+10800002)).toThrow();});
 it('候补截止不递补、可以退出',()=>{const e=event({maxPeople:2,promotionDeadline:t+3600000});for(const u of ['a','b','c'])act(e,'join',u);reconcile(e,t+3600000,[]);act(e,'leave','a',t+3700000);expect(e.participants.find(p=>p.userId==='c')?.status).toBe('waitlisted');act(e,'leave','c',t+3700010);expect(e.participants.find(p=>p.userId==='c')?.status).toBe('left');});
});
