import {describe,it,expect} from 'vitest';
import {applyCommand,conditions,createActivity,reconcile,isManager} from '../worker/engine';
import type {Activity,Notice,Rules} from '../worker/types';
const t=Date.UTC(2026,8,5,10);
const rules=(r:Partial<Rules>={}):Rules=>({minPeople:2,maxPeople:3,waitlist:true,recruitmentDeadline:t+3600000,startsAt:t+7200000,endsAt:t+10800000,registrationDeadline:t+6900000,promotionDeadline:t+6900000,repairMinutes:10,venueRequired:false,minTalks:0,minCohosts:0,minHosts:0,allowRoleOverlap:true,continuousVenue:true,continuousTalks:true,continuousCohosts:true,continuousHosts:true,addressVisibility:'participants',...r});
function event(r:Partial<Rules>={}):Activity{const e=createActivity({title:'测试咖啡',city:'Amsterdam',description:'',rules:rules(r)},'owner',t);applyCommand(e,{action:'publish'},'owner',t,[]);return e;}
function act(e:Activity,action:string,user:string,at=t+1000,more:Record<string,unknown>={}){const out:Notice[]=[];reconcile(e,at,out);applyCommand(e,{action,...more},user,at,out);return out;}
describe('确定性业务规则',()=>{
 it('校验规则与发布锁定',()=>{expect(()=>event({minPeople:4})).toThrow();const e=event();expect(()=>act(e,'edit','owner')).toThrow('锁定');});
 it('截止满足则成团，不足则取消且不能救活',()=>{const e=event();act(e,'join','a');act(e,'join','b');reconcile(e,t+3600001,[]);expect(e.status).toBe('confirmed');expect(e.receipts.at(-1)?.at).toBe(t+3600000);const bad=event();reconcile(bad,t+3600001,[]);expect(bad.status).toBe('cancelled');expect(()=>act(bad,'join','a',t+3600002)).toThrow();});
 it('退出优先候补并发入选通知',()=>{const e=event({maxPeople:2});for(const u of ['a','b','c'])act(e,'join',u);reconcile(e,t+3600000,[]);const out=act(e,'leave','a',t+3700000);expect(e.participants.find(p=>p.userId==='c')?.status).toBe('joined');expect(out.some(n=>n.userId==='c'&&n.subject.includes('入选'))).toBe(true);expect(e.repairs).toHaveLength(0);});
 it('始终维持最低人数，不足新报名不延长倒计时，补齐才解除',()=>{const e=event({minPeople:3,maxPeople:5});for(const u of ['a','b','c'])act(e,'join',u);reconcile(e,t+3600000,[]);act(e,'leave','a',t+3700000);const deadline=e.repairs[0].deadline;act(e,'leave','b',t+3701000);act(e,'join','d',t+3702000);expect(e.repairs[0].deadline).toBe(deadline);act(e,'join','f',t+3703000);expect(e.status).toBe('confirmed');expect(e.repairs).toHaveLength(0);});
 it('报名截止不阻止人数补齐，到期不足取消',()=>{const e=event({registrationDeadline:t+3600000});act(e,'join','a');act(e,'join','b');reconcile(e,t+3600000,[]);act(e,'leave','a',t+3700000);act(e,'join','c',t+3700100);expect(e.status).toBe('confirmed');act(e,'leave','b',t+3700200);reconcile(e,t+4400000,[]);expect(e.status).toBe('cancelled');});
 it('场地和人数独立异常，未审核提案无效',()=>{const e=event({venueRequired:true});act(e,'apply','v',t+1000,{kind:'venue',title:'场地',detail:'',address:'地址',capacity:3});act(e,'review','owner',t+2000,{applicationId:e.applications[0].id,approved:true});act(e,'join','a');act(e,'join','b');reconcile(e,t+3600000,[]);act(e,'withdraw','v',t+3700000,{applicationId:e.applications[0].id});act(e,'leave','a',t+3700100);expect(e.repairs.map(r=>r.key).sort()).toEqual(['people','venue']);act(e,'apply','v2',t+3700200,{kind:'venue',title:'新场地',detail:'',address:'地址2',capacity:3});expect(e.repairs).toHaveLength(2);act(e,'review','owner',t+3700300,{applicationId:e.applications[1].id,approved:true});expect(e.repairs.map(r=>r.key)).toEqual(['people']);});
  it('报名时保存偏好且已报名者可以更新',()=>{const e=event();act(e,'join','a',t+1000,{timePreference:'周六下午',placePreference:'Amsterdam'});expect(e.participants[0]).toMatchObject({timePreference:'周六下午',placePreference:'Amsterdam'});act(e,'join','a',t+2000,{timePreference:'周日下午',placePreference:'Utrecht'});expect(e.participants).toHaveLength(1);expect(e.participants[0]).toMatchObject({timePreference:'周日下午',placePreference:'Utrecht'});});
 it('活动结束是终态',()=>{const e=event();act(e,'join','a');act(e,'join','b');reconcile(e,t+10800001,[]);expect(e.status).toBe('completed');expect(()=>act(e,'join','c',t+10800002)).toThrow();});
 it('候补截止不递补、可以退出',()=>{const e=event({maxPeople:2,promotionDeadline:t+3600000});for(const u of ['a','b','c'])act(e,'join',u);reconcile(e,t+3600000,[]);act(e,'leave','a',t+3700000);expect(e.participants.find(p=>p.userId==='c')?.status).toBe('waitlisted');act(e,'leave','c',t+3700010);expect(e.participants.find(p=>p.userId==='c')?.status).toBe('left');});
});

it('交通多选与留言可更新清空，拒绝无效输入',()=>{const e=event();act(e,'join','a',t+1000,{transportPreferences:['public_transport','car'],registrationMessage:'大家好'});expect(e.participants[0]).toMatchObject({transportPreferences:['public_transport','car'],registrationMessage:'大家好'});act(e,'join','a',t+2000,{transportPreferences:[],registrationMessage:''});expect(e.participants[0]).toMatchObject({transportPreferences:[],registrationMessage:''});expect(()=>act(e,'join','a',t+3000,{transportPreferences:['plane']})).toThrow();expect(()=>act(e,'join','a',t+3000,{registrationMessage:'a'.repeat(501)})).toThrow();});

const slots=[{id:'sat',startsAt:t+7200000,endsAt:t+10800000},{id:'sun',startsAt:t+86400000,endsAt:t+90000000}];
it('时段投票不能替代最终确认，人数按最终时段计算',()=>{const e=event({timeSlots:slots});act(e,'join','a',t+1000,{availableSlotIds:['sat']});act(e,'join','b',t+1100,{availableSlotIds:['sun']});expect(conditions(e).find(c=>c.key==='people')?.current).toBe(0);expect(()=>act(e,'select_time','a',t+1200,{slotId:'sat'})).toThrow();act(e,'select_time','owner',t+1300,{slotId:'sun'});expect(e.rules.startsAt).toBe(slots[1].startsAt);expect(conditions(e).find(c=>c.key==='people')?.current).toBe(1);expect(e.participants[0].status).toBe('left');expect(()=>act(e,'select_time','owner',t+1400,{slotId:'sat'})).toThrow();reconcile(e,t+3600000,[]);expect(e.status).toBe('cancelled');});
it('未确认时间即使投票充足仍取消',()=>{const e=event({timeSlots:slots});for(const u of ['a','b'])act(e,'join',u,t+1000,{availableSlotIds:['sat','sun']});reconcile(e,t+3600000,[]);expect(e.status).toBe('cancelled');});
it('候选时段独立收集意向，最终席位与候补遵循顺序和可参加时间',()=>{const e=event({timeSlots:slots,maxPeople:2});act(e,'join','a',t+1000,{availableSlotIds:['sun']});for(const u of ['b','c','d'])act(e,'join',u,t+1000,{availableSlotIds:['sat']});act(e,'select_time','owner',t+2000,{slotId:'sat'});expect(e.participants.map(p=>p.status)).toEqual(['left','joined','joined','waitlisted']);act(e,'leave','b',t+2100);expect(e.participants[0].status).toBe('left');expect(e.participants[3].status).toBe('joined');expect(()=>act(e,'join','a',t+2200,{availableSlotIds:['sun']})).toThrow();reconcile(e,t+3600000,[]);expect(e.status).toBe('confirmed');});
it('拒绝无效时段和空投票，允许多选及修改',()=>{expect(()=>event({timeSlots:[slots[0],slots[0]]})).toThrow();const e=event({timeSlots:slots});expect(()=>act(e,'join','a',t+1000,{availableSlotIds:[]})).toThrow();expect(()=>act(e,'join','a',t+1000,{availableSlotIds:['missing']})).toThrow();act(e,'join','a',t+1000,{availableSlotIds:['sat','sun']});act(e,'join','a',t+2000,{availableSlotIds:['sun']});expect(e.participants[0].availableSlotIds).toEqual(['sun']);});

it('发起人发布不自动报名，主动报名才计入人数',()=>{const e=event();expect(e.participants).toHaveLength(0);expect(conditions(e).find(c=>c.key==='people')?.current).toBe(0);act(e,'join','owner');expect(conditions(e).find(c=>c.key==='people')?.current).toBe(1);act(e,'join','owner');expect(e.participants).toHaveLength(1);});

it('不开放候补时超额意向结束报名并通知',()=>{const e=event({timeSlots:slots,maxPeople:2,waitlist:false});for(const u of ['a','b','c'])act(e,'join',u,t+1000,{availableSlotIds:['sat']});const out=act(e,'select_time','owner',t+2000,{slotId:'sat'});expect(e.participants.map(p=>p.status)).toEqual(['joined','joined','left']);expect(out.some(n=>n.userId==='c'&&n.subject==='报名未入选')).toBe(true);});
it('退休类型不能新申请或批准，历史协办没有管理权',()=>{const e=event();for(const kind of ['talk','cohost'])expect(()=>act(e,'apply','a',t+1000,{kind,title:'申请',detail:''})).toThrow('MVP');e.applications.push({id:'old',userId:'co',kind:'cohost',title:'历史',detail:'',status:'pending',updatedAt:t});expect(()=>act(e,'review','owner',t+1000,{applicationId:'old',approved:true})).toThrow('MVP');e.applications[0].status='approved';expect(isManager(e,'co')).toBe(false);});
it('切换场地更新备用记录并通知原提供人',()=>{const e=event();for(const u of ['a','b'])act(e,'apply',u,t+1000,{kind:'venue',title:u,detail:'',address:'地址',capacity:3});act(e,'review','owner',t+2000,{applicationId:e.applications[0].id,approved:true});const out=act(e,'review','owner',t+3000,{applicationId:e.applications[1].id,approved:true});expect(e.applications[0]).toMatchObject({status:'pending',updatedAt:t+3000,reviewedBy:'owner'});expect(out.some(n=>n.userId==='a'&&n.subject==='场地已转为备用')).toBe(true);});
