import {beforeAll,afterAll,beforeEach,describe,it,expect} from 'vitest';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {readFileSync} from 'node:fs';
import {execute,insertActivity,load,project} from '../worker/store';
import type {Env,Rules,User} from '../worker/types';
let mf:Miniflare,env:Env;
const user=(id:string):User=>({id,email:`${id}@test.invalid`,nickname:id,publicNickname:false});
const base=():Rules=>{const t=Date.now();return {minPeople:1,maxPeople:2,waitlist:true,recruitmentDeadline:t+3600000,startsAt:t+7200000,endsAt:t+10800000,registrationDeadline:t+6900000,promotionDeadline:t+6900000,repairMinutes:10,venueRequired:false,minTalks:0,minCohosts:0,minHosts:0,allowRoleOverlap:true,continuousVenue:true,continuousTalks:true,continuousCohosts:true,continuousHosts:true,addressVisibility:'participants'};};
beforeAll(async()=>{mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:['DB'],compatibilityDate:'2026-09-05'}));const DB=await mf.getD1Database('DB');env={DB:DB as unknown as D1Database,APP_ENV:'test',ASSETS:{} as Fetcher};for(const f of ['0001_events.sql','0002_identity.sql'])for(const s of readFileSync(new URL(`../migrations/${f}`,import.meta.url),'utf8').split(';').filter(s=>s.trim()))await DB.prepare(s).run();});
afterAll(async()=>{await mf?.dispose();});
beforeEach(async()=>{for(const table of ['activities','audit','outbox','users'])await env.DB.prepare(`DELETE FROM ${table}`).run();});
async function published(){const e=await insertActivity(env,{title:'测试',city:'Amsterdam',description:'',rules:base()},user('owner'));return execute(env,e.id,{action:'publish'},user('owner'),'pub');}
describe('D1事务与公开投影',()=>{
 it('并发抢名额不超额，幂等不重复审计',async()=>{const e=await published();await Promise.all(Array.from({length:8},(_,i)=>execute(env,e.id,{action:'join'},user(`u${i}`),`join-${i}`)));const after=await load(env,e.id);expect(after.participants.filter(p=>p.status==='joined')).toHaveLength(2);expect(after.participants.filter(p=>p.status==='waitlisted')).toHaveLength(6);await execute(env,e.id,{action:'join'},user('u0'),'join-0',0);expect((await load(env,e.id)).version).toBe(after.version);const audit=await env.DB.prepare('SELECT count(*) n FROM audit WHERE event_id=?').bind(e.id).first<{n:number}>();expect(audit!.n).toBe(10);});
 it('并发退出只向每位入选者通知一次',async()=>{const e=await published();for(const id of ['a','b','c','d'])await execute(env,e.id,{action:'join'},user(id),`j${id}`);await Promise.all(['a','b'].map(id=>execute(env,e.id,{action:'leave'},user(id),`l${id}`)));const out=await env.DB.prepare("SELECT user_id FROM outbox WHERE subject='候补已入选'").all<{user_id:string}>();expect(out.results.map(r=>r.user_id).sort()).toEqual(['c','d']);});
 it('晚报名不能改变截止判定',async()=>{const e=await published();await expect(execute(env,e.id,{action:'join'},user('late'),'late',undefined,()=>e.rules.recruitmentDeadline+1)).rejects.toThrow();expect((await load(env,e.id)).status).toBe('cancelled');expect((await load(env,e.id)).participants).toHaveLength(0);});
 it('私有地址、邮箱和申请备注不公开',async()=>{const e=await published();await env.DB.prepare('INSERT INTO users(id,email,nickname,public_nickname) VALUES(?,?,?,?)').bind('a','private@test.invalid','私人昵称',0).run();await execute(env,e.id,{action:'join'},user('a'),'ja');let s=await execute(env,e.id,{action:'apply',kind:'venue',title:'场地',detail:'private@test.invalid',address:'SECRET ADDRESS',capacity:2},user('a'),'venue');s=await execute(env,e.id,{action:'review',applicationId:s.applications[0].id,approved:true},user('owner'),'approve');const anon=JSON.stringify(await project(env,s,null));expect(anon).not.toContain('SECRET ADDRESS');expect(anon).not.toContain('private@test.invalid');expect(anon).not.toContain('私人昵称');expect(JSON.stringify(await project(env,s,user('a')))).toContain('SECRET ADDRESS');});
 it('草稿隔离且他人不可查看',async()=>{const e=await published();const draft=await insertActivity(env,{title:'草稿',city:'Rotterdam',description:'',rules:base()},user('another'));await execute(env,e.id,{action:'join'},user('a'),'join');expect((await load(env,draft.id)).participants).toHaveLength(0);await expect(project(env,draft,user('a'))).rejects.toThrow();});
 it('偏好只按汇总公开并向本人回读',async()=>{let e=await published();e=await execute(env,e.id,{action:'join',timePreference:'周六下午',placePreference:'Amsterdam'},user('a'),'pref-a');e=await execute(env,e.id,{action:'join',timePreference:'周六下午',placePreference:'Utrecht'},user('b'),'pref-b');const anon=await project(env,e,null);expect(anon.preferenceSummary).toMatchObject({times:[{label:'周六下午',count:2}],places:[{label:'Amsterdam',count:1},{label:'Utrecht',count:1}]});expect(JSON.stringify(anon.participants)).not.toContain('周六下午');const mine=await project(env,e,user('a'));expect(mine.myParticipation).toMatchObject({timePreference:'周六下午',placePreference:'Amsterdam'});});
});
