const priority=['Amsterdam','Rotterdam','Den Haag','Utrecht','Amstelveen'];
const second=['Delft','Eindhoven','Enschede','Groningen','Heerlen','Hoofddorp','Leiden','Maastricht','Nijmegen','Tilburg','Wageningen','Zaandam'];
const others=['Alkmaar','Almere','Amersfoort','Apeldoorn','Arnhem','Assen','Breda','Deventer','Dordrecht','Gouda','Haarlem','Hilversum','Leeuwarden','Lelystad','Middelburg','Roermond',"’s-Hertogenbosch",'Venlo','Zaanstad','Zoetermeer','Zwolle'];
const aliases={Amsterdam:'阿姆斯特丹 阿姆',Rotterdam:'鹿特丹', 'Den Haag':'海牙 the hague s gravenhage',Utrecht:'乌特勒支',Amstelveen:'阿姆斯特尔芬 阿姆斯特芬',Delft:'代尔夫特',Eindhoven:'埃因霍温',Enschede:'恩斯赫德',Groningen:'格罗宁根',Hoofddorp:'霍夫多普',Leiden:'莱顿',Maastricht:'马斯特里赫特',Nijmegen:'奈梅亨',Tilburg:'蒂尔堡',Wageningen:'瓦赫宁根',Zaandam:'赞丹 扎安丹 zandam',Haarlem:'哈勒姆',"’s-Hertogenbosch":'den bosch 登博斯'};
const normalize=s=>s.normalize('NFKC').toLowerCase().trim();
export function cityGroups(extra=[]){const known=new Set([...priority,...second].map(normalize));const rest=[...new Map([...others,...extra].filter(Boolean).filter(c=>!known.has(normalize(c))).map(c=>[normalize(c),c])).values()].sort((a,b)=>a.localeCompare(b,'nl'));return [['常用城市',priority],['大学城及周边',second],['其他城市',rest]];}
export function cityPicker(el,value='',extra=[]){
 const id='cities-'+crypto.randomUUID(),input=el('input',{name:'city',value,required:true,maxLength:80,role:'combobox',autocomplete:'off','aria-autocomplete':'list','aria-expanded':'false','aria-controls':id,placeholder:'选择城市，或输入城市名'});
 const list=el('div',{id,role:'listbox',class:'city-options',hidden:true});let matches=[],active=-1;
 const close=()=>{list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');active=-1;};
 const choose=city=>{input.value=city;close();input.focus();input.dispatchEvent(new Event('change',{bubbles:true}));};
 const render=(query='')=>{matches=[];active=-1;list.replaceChildren();for(const [title,cities] of cityGroups(extra)){const found=cities.filter(c=>normalize(c+' '+(aliases[c]||'')).includes(normalize(query)));if(!found.length)continue;list.append(el('div',{class:'city-group','aria-hidden':'true'},title));for(const city of found){const index=matches.length;matches.push(city);list.append(el('div',{role:'option',id:id+'-'+index,'aria-selected':'false',onpointerdown:e=>e.preventDefault(),onclick:()=>choose(city)},city));}}if(!matches.length)list.append(el('div',{class:'city-group'},'没有匹配城市，可直接填写城市全名。'));list.hidden=false;input.setAttribute('aria-expanded','true');};
 input.oninput=()=>render(input.value);input.onclick=()=>{if(list.hidden)render();};input.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();close();}else if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();if(list.hidden)render();if(!matches.length)return;active=(active+(e.key==='ArrowDown'?1:-1)+matches.length)%matches.length;list.querySelectorAll('[role=option]').forEach((n,i)=>n.setAttribute('aria-selected',String(i===active)));const option=list.querySelectorAll('[role=option]')[active];input.setAttribute('aria-activedescendant',option.id);option.scrollIntoView({block:'nearest'});}else if(e.key==='Enter'&&!list.hidden&&active>=0){e.preventDefault();choose(matches[active]);}};
 input.onchange=()=>{const all=[...priority,...second,...others,...extra];const canonical=all.find(c=>normalize(c)===normalize(input.value))||Object.keys(aliases).find(c=>aliases[c].split(' ').includes(normalize(input.value)));if(canonical)input.value=canonical;};
 const toggle=el('button',{type:'button',class:'city-toggle','aria-label':'展开城市列表',onclick:()=>{if(list.hidden){input.focus();render();}else close();}},'⌄');
 const root=el('div',{class:'field city-picker'},el('label',{'for':id+'-input'},'城市'),el('div',{class:'city-input'},input,toggle),list);input.id=id+'-input';root.onfocusout=e=>{if(!root.contains(e.relatedTarget))close();};return root;
}
