import {canonicalCity,cityCatalog,normalizeCity} from './city-catalog.js';

export function cityGroups(extra=[]){const names=new Set(cityCatalog.map(city=>normalizeCity(city.name)));const priority=cityCatalog.filter(city=>city.group==='priority').map(city=>city.name),second=cityCatalog.filter(city=>city.group==='second').map(city=>city.name),other=cityCatalog.filter(city=>city.group==='other').map(city=>city.name);const rest=[...new Map([...other,...extra].filter(Boolean).filter(city=>!names.has(normalizeCity(city))||other.includes(city)).map(city=>[normalizeCity(city),city])).values()].sort((a,b)=>a.localeCompare(b,'nl'));return [['常用城市',priority],['大学城及周边',second],['其他城市',rest]];}
export function cityPicker(el,value='',extra=[]){
 const id='cities-'+crypto.randomUUID(),input=el('input',{name:'city',value,required:true,maxLength:80,role:'combobox',autocomplete:'off','aria-autocomplete':'list','aria-expanded':'false','aria-controls':id,placeholder:'选择城市，或输入城市名'});
 const list=el('div',{id,role:'listbox',class:'city-options',hidden:true});let matches=[],active=-1;
 const close=()=>{list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');active=-1;};
 const choose=city=>{input.value=city;close();input.focus();input.dispatchEvent(new Event('change',{bubbles:true}));};
 const render=(query='')=>{matches=[];active=-1;list.replaceChildren();for(const [title,cities] of cityGroups(extra)){const found=cities.filter(name=>{const city=cityCatalog.find(item=>item.name===name);return normalizeCity([name,...(city?.aliases||[])].join(' ')).includes(normalizeCity(query));});if(!found.length)continue;list.append(el('div',{class:'city-group','aria-hidden':'true'},title));for(const city of found){const index=matches.length;matches.push(city);list.append(el('div',{role:'option',id:id+'-'+index,'aria-selected':'false',onpointerdown:e=>e.preventDefault(),onclick:()=>choose(city)},city));}}if(!matches.length)list.append(el('div',{class:'city-group'},'没有匹配城市，可直接填写城市全名。'));list.hidden=false;input.setAttribute('aria-expanded','true');};
 input.oninput=()=>render(input.value);input.onclick=()=>{if(list.hidden)render();};input.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();close();}else if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();if(list.hidden)render();if(!matches.length)return;active=(active+(e.key==='ArrowDown'?1:-1)+matches.length)%matches.length;list.querySelectorAll('[role=option]').forEach((n,i)=>n.setAttribute('aria-selected',String(i===active)));const option=list.querySelectorAll('[role=option]')[active];input.setAttribute('aria-activedescendant',option.id);option.scrollIntoView({block:'nearest'});}else if(e.key==='Enter'&&!list.hidden&&active>=0){e.preventDefault();choose(matches[active]);}};
 input.onchange=()=>{const canonical=canonicalCity(input.value)||extra.find(city=>normalizeCity(city)===normalizeCity(input.value));if(canonical)input.value=canonical;};
 const toggle=el('button',{type:'button',class:'city-toggle','aria-label':'展开城市列表',onclick:()=>{if(list.hidden){input.focus();render();}else close();}},'⌄');
 const root=el('div',{class:'field city-picker'},el('label',{'for':id+'-input'},'城市'),el('div',{class:'city-input'},input,toggle),list);input.id=id+'-input';root.onfocusout=e=>{if(!root.contains(e.relatedTarget))close();};return root;
}
