// CLI reference for terminal users and agents; no requests are executed here.
export function renderCliDocs(root){
root.innerHTML=`<article class="cli-reference"><p class="eyebrow">DOCS / CLI REFERENCE</p><h1>dc-flow</h1><p>给终端用户和 Agent 的 Data Coffee 命令参考。与网页共用 API、身份和权限。</p>
<nav class="cli-toc" aria-label="文档目录"><a href="#cli/setup">开始使用</a> · <a href="#cli/commands">命令</a> · <a href="#cli/auth">认证</a> · <a href="#cli/agents">Agent 调用</a></nav>
<section id="setup"><h2>安装与开始使用</h2><p>需要 Git 和 Node.js 22+（包含 npm）。当前从 <a href="https://github.com/zhaidewei/data_coffee" target="_blank" rel="noopener noreferrer">GitHub 源码</a>安装，尚未发布 npm 安装包。</p><pre><code>git clone https://github.com/zhaidewei/data_coffee.git
cd data_coffee/app
npm link
dc-flow --help</code></pre><h3>连接测试站点</h3><p>在终端执行以下命令。公开活动无需登录即可查询：</p><pre><code>export DATA_COFFEE_BASE_URL=https://data-coffee-dev.dewei-zhai.workers.dev
dc-flow events list
dc-flow events get EVENT_ID</code></pre><p>将 EVENT_ID 替换为列表返回的活动 id。export 对当前终端会话生效，新开终端时需要重新设置。也可以逐次传入 <code>--base-url</code>。不指定地址时默认连接 <code>http://localhost:8787</code>；远端地址必须使用 HTTPS，且不能带路径、查询参数或凭证。</p><p>不安装全局命令也可以在 app 目录执行 <code>node cli/dc-flow.mjs --help</code>。</p></section>
<section id="commands"><h2>命令参考</h2><div class="cli-table"><table><thead><tr><th>命令</th><th>用途 / 请求体</th></tr></thead><tbody>
<tr><td><code>events list</code></td><td>列出可见活动，GET /api/events</td></tr><tr><td><code>events get &lt;id&gt;</code></td><td>读取活动详情与当前 version</td></tr><tr><td><code>events create --data @draft.json</code></td><td>创建草稿；title、city、description、rules 与 Web API 一致</td></tr><tr><td><code>events action &lt;id&gt; &lt;action&gt;</code></td><td>提交动作，必须指定 --version 和 --key</td></tr><tr><td><code>auth request --data -</code></td><td>请求邮箱验证码：{email}，会发送邮件</td></tr><tr><td><code>auth verify --data -</code></td><td>验证登录：{email,code,nickname}</td></tr><tr><td><code>auth me</code></td><td>读取当前用户</td></tr><tr><td><code>auth export</code></td><td>导出本人的资料、活动关系、通知与安全元数据</td></tr><tr><td><code>auth logout</code></td><td>注销当前会话</td></tr></tbody></table></div>
<p>动作名称：<code>edit describe raise_capacity publish select_time join leave reply_registration apply review withdraw revoke cancel</code>。其中 <code>raise_capacity</code> 仅供发布者在报名截止前上调人数上限，请求体为 <code>{"maxPeople":12}</code>；<code>reply_registration</code> 仅供发布者回复报名留言，需要 participantId 和 reply。可执行性与附加字段由 API 根据身份和活动状态校验。</p>
<h3>参数</h3><ul><li><code>--data</code>：JSON 对象、@文件，或 - 从 stdin 读取。</li><li><code>--version</code>：读取到的当前非负整数版本。</li><li><code>--key</code>：一次动作的幂等键，1–100 个字母、数字、冒号、下划线或连字符。</li><li><code>--token-stdin</code>：从 stdin 读取个人访问令牌；不能与 --data - 同用。</li><li><code>--session-stdin</code>：从 stdin 读取会话；不能与 --data - 同用。</li><li><code>--session-only</code>：仅用于 auth verify，输出 {sessionToken}，供安全管道捕获。</li></ul></section>
<section id="auth"><h2>认证与会话</h2><h3>推荐：个人 API token</h3><p>在网页中登录并创建个人访问令牌，将它保存到你使用的本地密钥管理工具。已安装 secret CLI 的用户可以这样验证身份：</p><pre><code>secret get YOUR_TOKEN_NAME | dc-flow --token-stdin auth me</code></pre><p>将 YOUR_TOKEN_NAME 替换为你保存令牌时使用的名称。secret CLI 是独立工具，不随 dc-flow 安装；读取语法以你的工具为准。先按上方示例设置测试站点地址。每次需要认证的命令都需重新注入令牌，CLI 不会记住登录凭证。</p><p>推荐在网页登录后创建个人访问令牌，通过 <code>DATA_COFFEE_TOKEN</code> 或 <code>--token-stdin</code> 注入。格式为 dcf_ 加 64 位小写十六进制字符，通过 Authorization: Bearer 发送。两个 token 来源同时提供、或 token 与会话同时提供时拒绝执行。</p><p>Agent 在调用点使用本地 secret CLI 读取令牌，将输出管道接到 <code>dc-flow auth me --token-stdin</code>；读取参数以本机 secret 帮助为准。令牌不能进入命令参数、日志或文件。--token-stdin 与 --data - 不能同用，可通过 @文件提供动作请求体。</p><h3>导出我的数据</h3><p><code>auth export</code> 返回当前用户的资料、活动关系、本人操作记录、通知、令牌元数据和会话到期时间。导出不包含令牌或会话密文，也不包含其他成员的私密资料。</p><pre><code>secret get YOUR_TOKEN_NAME | dc-flow --token-stdin auth export &gt; my-data-coffee-export.json</code></pre><p>导出文件包含个人数据，请存放在自己控制的位置。</p><p>邮箱验证码登录保留作为备用。会话通过 <code>DATA_COFFEE_SESSION</code> 或 <code>--session-stdin</code> 注入；stdin 接受 64 位十六进制 token 或 {sessionToken} JSON。CLI 不保存凭证，也不接受命令行 token。</p><p>Agent 应在调用点通过本地 secret CLI 读取会话并管道注入，避免将会话或验证码写入命令参数、日志和文件。验证登录时，用 stdin 传入验证码请求体，并捕获 --session-only 输出。</p></section>
<section id="agents"><h2>Agent 调用流程</h2><ol><li>先 events get 读取当前状态、版本和候选时段。</li><li>确认所需动作，准备非敏感 JSON 请求体和唯一幂等键。</li><li>提交动作；成功后再次读取活动核对结果。</li></ol><pre><code>dc-flow events get EVENT_ID
# 将 VERSION 替换为刚读取的版本；个人访问令牌由运行环境安全注入
# join.json 根据活动时段包含所需报名偏好
 dc-flow events action EVENT_ID join \\
  --version VERSION --key join-unique-001 --data @join.json
 dc-flow events get EVENT_ID</code></pre>
<p>成功输出 stdout JSON，错误输出 stderr JSON；--help 输出帮助文本。自动化建议直接使用 dc-flow 或 node 脚本，避免 npm 的额外输出。</p><div class="cli-table"><table><thead><tr><th>退出码</th><th>处理方式</th></tr></thead><tbody><tr><td>0</td><td>成功</td></tr><tr><td>1</td><td>网络或 API 错误；写入结果可能未知，先读取核对</td></tr><tr><td>2</td><td>参数错误，修正输入</td></tr><tr><td>3</td><td>认证或权限错误</td></tr><tr><td>4</td><td>版本冲突，重新读取并判断动作</td></tr></tbody></table></div>
<p>CLI 不自动重试。重试同一次 action 必须复用原始 key、version 和请求体；业务意图改变时使用新 key。创建草稿没有幂等支持，超时后先查列表，避免重复创建。</p><p>请求超时 30 秒，拒绝重定向。目前没有分页、删除已发布活动、自动刷新登录。</p></section></article>`;
const section=location.hash.split('/')[1];if(section)root.querySelector('#'+({'setup':'setup','commands':'commands','auth':'auth','agents':'agents'}[section]||'setup'))?.scrollIntoView();
}
